version: "3.8"

services:
  caddy:
    image: caddy:latest
    networks:
      - vps_shield_net
    configs:
      - source: caddy_config_v2
        target: /etc/caddy/Caddyfile
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == racknerd-edc1bc8
      restart_policy:
        condition: any

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    networks:
      - vps_shield_net
    environment:
      - TUNNEL_TOKEN=${VPS_TUNNEL_TOKEN:-}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == racknerd-edc1bc8
      restart_policy:
        condition: any

networks:
  vps_shield_net:
    driver: overlay
    attachable: true

configs:
  caddy_config_v2:
    file: ./Caddyfile
