apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-master
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  nodeSelector: "master"
