apiVersion: batch/v1
kind: CronJob
metadata:
  name: lectures-notifier-et-10m
  namespace: default
spec:
  schedule: "*/5 10-18 * * *"
  timeZone: America/New_York
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          dnsConfig:
            options:
              - name: ndots
                value: "1"
              - name: single-request-reopen
          containers:
            - name: notifier
              image: ghcr.io/gordonpn/lectures-notifier:main
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: lectures-notifier-secrets
