#!/bin/sh

cru a ddns_update "0 * * * * /jffs/scripts/ddns-start"

# Your API Token
API_TOKEN=""
# Your zone id, hex16 string
ZONE_ID=""
# Your DNS record name, e.g. sub.example.com
RECORD_NAME="gordon-pn.com"
# TTL in seconds (1=auto)
RECORD_TTL="1"

get_dns_record_ids() {
  record_name=$1
  type=$2
  api_token=$3
  zone_id=$4

  RESPONSE="$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records?type=${type}&name=${record_name}" \
    -H "Authorization: Bearer ${api_token}" \
    -H "Content-Type:application/json")"

  echo "$RESPONSE" | python -c "
import sys, json

data = json.load(sys.stdin)
for record in data['result']:
    print (record['id'])"
}

update_dns_record() {
  record_name=$1
  record_id=$2
  type=$3
  ip=$4
  record_ttl=$5
  api_token=$6
  zone_id=$7

  curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records/${record_id}" \
    -H "Authorization: Bearer ${api_token}" \
    -H "Content-Type: application/json" \
    --data "{\"type\":\"${type}\",\"name\":\"${record_name}\",\"content\":\"${ip}\",\"ttl\":${record_ttl},\"proxied\":true}"
}

RESULT=true

# Update IPv4
IPv4=$(curl http://ipecho.net/plain)
A_RECORD_IDS=$(get_dns_record_ids $RECORD_NAME A "$API_TOKEN" "$ZONE_ID")

for A_RECORD_ID in $A_RECORD_IDS; do
  RESPONSE="$(update_dns_record $RECORD_NAME "$A_RECORD_ID" A "$IPv4" $RECORD_TTL "$API_TOKEN" "$ZONE_ID")"
  echo "$RESPONSE" | grep '"success":\ *true' >/dev/null

  if [ $? -eq 0 ]; then
    logger "Updated A record for ${RECORD_NAME} to ${IPv4}"
  else
    logger "Unable to update A record for ${RECORD_NAME}"
    RESULT=false
  fi
done

if [ "$RESULT" = true ]; then
  /sbin/ddns_custom_updated 1
else
  /sbin/ddns_custom_updated 0
fi
