networkHealth:
  discoverTarget:
    image:
      repository: bitnami/kubectl
      tag: latest
      pullPolicy: IfNotPresent
  echo:
    serviceName: ""
    daemonSetName: ""
    appLabel: ""
  cronJobs:
    healthCheckName: ""
    crossNodeCheckName: ""
  rbac:
    checkerName: ""
