version: "3.8"

services:
  whoami:
    image: traefik/whoami:latest
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == master
      restart_policy:
        condition: any
