name: GitOps Loop

on:
  push:
    branches:
      - master
    paths:
      - 'k8s/**'
      - 'Taskfile.yaml'
  workflow_dispatch:

jobs:
  gitops:
    name: Sync GitOps Releases
    runs-on: home-lab-runners
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helmfile
        uses: mamezou-tech/setup-helmfile@v2.2.0

      - name: Apply Charts via Helmfile
        run: task charts:apply
